"""Generate docs/05-data-dictionary.md from the warehouse itself.

A dictionary maintained by hand drifts from the schema within a release or two.
This one is read out of DuckDB's catalog, so it cannot describe a column that no
longer exists. The prose notes below are keyed by table and merged in.
"""

import sys

import duckdb

from pipeline.config import ROOT, WAREHOUSE

LAYER = {
    "stg_": "Staging", "dim_": "Dimension", "fct_": "Fact",
    "int_": "Intermediate", "ref_": "Reference", "mart_": "Mart",
}

NOTES = {
    "stg_airport": "Airport reference from OpenFlights plus four hand-added overrides. The timezone column is load-bearing: without it no clock field in the BTS feed can be compared across airports.",
    "stg_flight": "The BTS extract with every clock field resolved to UTC. Arrival instants are derived forward from the departure instant using scheduled block time and reported delay, which has no date-wrap edge cases.",
    "dim_airport": "Airports appearing in the window. `size_band` is derived from share of departures using the FAA hub thresholds — close to the official categories but not identical, since the FAA uses enplanements.",
    "dim_carrier": "Operating carriers. BTS reports the operator, not the marketing brand: a United-branded regional flight appears under the regional's code.",
    "dim_date": "Calendar with federal holidays and travel-period flags. The travel period matters more than the holiday — Thanksgiving Day itself is one of the quietest flying days of the year.",
    "fct_flight": "One row per scheduled leg. Carries the root/inherited delay split that the rest of the project depends on.",
    "int_rotation_leg": "Legs chained by tail number into the sequence each airframe actually flew. `is_continuation` requires the previous leg to have landed where this one departs.",
    "ref_min_turn": "Minimum feasible turn per carrier and station, measured as the 5th percentile of turns actually achieved.",
    "ref_cost_assumption": "Cost rates in one auditable place. A4A 2025 direct cost per block minute, applied to all years in constant dollars.",
    "fct_rotation_leg": "Rotation legs with turn slack, the propagation prediction, and cascade identifiers. `cascade_position = 0` marks the leg that started a chain.",
    "mart_carrier_monthly": "Carrier scorecard. Every rate has cancelled and diverted flights in the denominator.",
    "mart_airport_daily": "Station performance by day, from the departure side.",
    "mart_route_reliability": "Route scorecard, limited to routes with 500+ flights in the window.",
    "mart_cascade": "One row per cascade: a root delay and everything it went on to break.",
    "mart_turn_slack_opportunity": "Buffer simulation by carrier and station, ranked. The deliverable behind recommendation R-3.",
}

ORDER = ["stg_", "dim_", "fct_", "int_", "ref_", "mart_"]


def main() -> int:
    if not WAREHOUSE.exists():
        print("warehouse not built", file=sys.stderr)
        return 1
    con = duckdb.connect(str(WAREHOUSE), read_only=True)
    tables = [r[0] for r in con.execute("""
        SELECT table_name FROM information_schema.tables
        WHERE table_schema = 'main' ORDER BY table_name
    """).fetchall()]
    tables.sort(key=lambda t: (next((i for i, p in enumerate(ORDER) if t.startswith(p)), 99), t))

    lines = [
        "# 05 — Data Dictionary",
        "",
        "*Generated by `python -m analysis.data_dictionary`, read from the warehouse "
        "catalog. Do not edit by hand.*",
        "",
        "---",
        "",
    ]
    for t in tables:
        layer = next((v for k, v in LAYER.items() if t.startswith(k)), "Other")
        rows = con.execute(f"SELECT count(*) FROM {t}").fetchone()[0]
        lines += [f"## `{t}`", "", f"**{layer}** · {rows:,} rows", ""]
        if t in NOTES:
            lines += [NOTES[t], ""]
        lines += ["| Column | Type |", "|---|---|"]
        for name, dtype in con.execute(f"""
            SELECT column_name, data_type FROM information_schema.columns
            WHERE table_name = '{t}' ORDER BY ordinal_position
        """).fetchall():
            lines.append(f"| `{name}` | {dtype} |")
        lines += [""]

    path = ROOT / "docs" / "05-data-dictionary.md"
    path.write_text("\n".join(lines))
    print(f"{len(tables)} tables -> {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
